### PR TITLE
enabled graphiql

### PR DESCRIPTION
**Pull request by hbutau**
I was getting errors when opening the browser to the url <http://localhost:3000>, and inspecting the javascript console. So i enabled graphiql. I dont know was it meant to be run without graphiql? And what am I supposed to get in the console. I am new to graphql and  apollo

### CODE REVIEW

**Comment by farskipper** [comment]
Oh yeah, I think adding graphiql is a good idea. Thanks!

What error message were you getting?

**Comment by farskipper** [comment]
Also, I just added a description on the blank http://localhost:3000 and a link to the graphiql

**Comment by hbutau** [comment]
Thanks @farskipper . The image below shows the error. Maybe there is something I am doing wrong.
jscript

**Comment by farskipper** [comment]
Oh yeah, this warning is because the page doesn't specify encoding. The page response is here: https://github.com/farskipper/vanilla-js-apollo-graphql-full-stack-playground/blob/master/server.js#L45

The second line is as expected. Coming from here: https://github.com/farskipper/vanilla-js-apollo-graphql-full-stack-playground/blob/master/client.js#L21

**Pull request merged**
